### ISSUE TITLE
Traefik Dashboard - 404

### ISSUE THREAD

**Issue by VictorGil-Ops** [tlex/traefik-oauth2-proxy#1]
Hi,

i have a 404 code trying connect from my dasborad with "https://traefik.mydomian.com/dashboard".

I configure de Google API and Cloudflare API, the others apps are correct login with  oauth2.

Thanks.

This is my config:

  `traefik.http.middlewares.default-compress.compress: 'true'                                                  `
  `traefik.http.middlewares.default-http.redirectScheme.scheme: https                                          `
  `traefik.http.middlewares.default-http.redirectScheme.permanent: 'true'                                      `
  `traefik.http.middlewares.default-https.chain.middlewares: default-compress                                  `
  `traefik.http.routers.default-redirect.entrypoints: http                                                     `
  `traefik.http.routers.default-redirect.middlewares: default-http                                             `
  `traefik.http.routers.default-redirect.rule: "HostRegexp(`{any:.*}`)"                                        `
  `traefik.http.routers.default-redirect.service: noop@internal                                                `
  `traefik.http.routers.traefik.entrypoints: https                                                             `
  `traefik.http.routers.traefik.middlewares: oauth-signin,oauth-verify,default-https                           `
  `traefik.http.routers.traefik.rule: "Host(`traefik.${DOMAIN?err}`) && PathPrefix(`/api`, `/dashboard`)"      `
  `traefik.http.routers.traefik.tls.certResolver: 'default'                                                    `
  `traefik.http.routers.traefik.service: api@internal                                                          `
  `traefik.http.services.traefik.loadbalancer.server.port: '80'                                                `
  `ports:                                                                                                      `
  `- target: 80                                                                                                `
  `  published: 80                                                                                             `
  `  protocol: tcp                                                                                             `
  `  mode: host                                                                                                `
  `- target: 443                                                                                               `
  `  published: 443                                                                                            `
  `  protocol: tcp                                                                                             `
  `  mode: host                                                                                                `
  `volumes:                                                                                                    `
  `- /var/run/docker.sock:/var/run/docker.sock                                                                 `
  `- ./folders/traefik:/etc/traefik/acme                                                                       `
 e`nvironment:                                                                                                 `
  `CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN?err}                                                                   `
  `CF_ZONE_API_TOKEN: ${CF_ZONE_API_TOKEN?err}                                                                 `
 c`ommand:                                                                                                     `
  `- --accesslog=true                                                                                          `
  `- --accesslog.fields.defaultmode=keep                                                                       `
  `- --accesslog.fields.headers.defaultmode=keep                                                               `
  `- --api.dashboard=true                                                                                      `
  `- --api.insecure=true                                                                                       `
  `# For the example only. Remove it for production!                                                           `
  `#- --certificatesResolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory     `
  `- --certificatesResolvers.default.acme.dnsChallenge.provider=cloudflare                                     `
  `- --certificatesResolvers.default.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53                         `
  `- --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json                                  `
  `- --entrypoints.http.address=:80                                                                            `
  `- --entrypoints.https.address=:443                                                                          `
  `- --log.level=INFO                                                                                          `
  `- --metrics.prometheus=true                                                                                 `
  `- --providers.docker.endpoint=unix:///var/run/docker.sock                                                   `
  `- --providers.docker.defaultRule=Host(`{{ index .Labels "ai.ix.fqdn"}}`)                                    `
  `- --providers.docker.exposedByDefault=false                                                                 `

**Comment by tlex** [comment]
Have you tried adding `/` at the end of the url?

Citing https://doc.traefik.io/traefik/operations/dashboard/#the-dashboard:
> The trailing slash `/` in `/dashboard/` is mandatory

**Comment by VictorGil-Ops** [comment]
> Have you tried adding `/` at the end of the url?
> 
> Citing https://doc.traefik.io/traefik/operations/dashboard/#the-dashboard:
> 
> > The trailing slash `/` in `/dashboard/` is mandatory

**Comment by VictorGil-Ops** [comment]
OMG!! I had not added it...

thank tlex!!
